// Portfolio data generated from /public/images/Portfolio folders
export interface PortfolioItem {
  id: string;
  name: string;
  industry: string;
  description: string;
  services: string[];
  image: string;
  images: string[];
  websiteUrl?: string;
}

export const portfolioData: PortfolioItem[] = [
  {
    id: "six-brothers-removalists",
    name: "Six Brothers Removalists",
    industry: "Moving & Relocation",
    description: "One of Australia's top removalist companies providing professional residential and commercial moving services across Sydney and NSW",
    services: ["Web Design", "SEO", "Google Ads", "Branding"],
    image: "/images/Portfolio/Six Brothers Removalists/Six Brothers Removalist.webp",
    images: [
      "/images/Portfolio/Six Brothers Removalists/Six Brothers Removalist.webp",
      "/images/Portfolio/Six Brothers Removalists/Web design for Removalist.webp",
    ],
    websiteUrl: "https://www.sixbrothersremovalist.com.au/",
  },
  {
    id: "osan-ability",
    name: "OSAN Ability",
    industry: "NDIS Provider",
    description: "Leading NDIS provider offering comprehensive disability support services including full-service digital marketing: branding, website, SEO, and advertising",
    services: ["Branding", "Web Design", "Google Ads", "SEO", "Social Media"],
    image: "/images/Portfolio/OSAN Ability/OSAN Ability.webp",
    images: [
      "/images/Portfolio/OSAN Ability/OSAN Ability.webp",
      "/images/Portfolio/OSAN Ability/OSAN Ability 1.webp",
      "/images/Portfolio/OSAN Ability/OSAN Ability 2.webp",
      "/images/Portfolio/OSAN Ability/OSAN Ability 3.webp",
      "/images/Portfolio/OSAN Ability/OSAN Ability 4.webp",
      "/images/Portfolio/OSAN Ability/OSAN Ability 5.webp",
    ],
    websiteUrl: "https://www.osanability.com.au/",
  },
  {
    id: "gps-vehicle-inspections",
    name: "GPS Vehicle Inspections",
    industry: "Automotive Inspection",
    description: "Mobile pre-purchase vehicle inspection services with experienced mechanics delivering comprehensive reports within 24 hours",
    services: ["Branding", "Web Design", "SEO", "Google Ads", "Social Media"],
    image: "/images/Portfolio/GPS Vehicle Inspections/GPS Vehicle inspection.webp",
    images: [
      "/images/Portfolio/GPS Vehicle Inspections/GPS Vehicle inspection.webp",
      "/images/Portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 1.webp",
      "/images/Portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 2.webp",
      "/images/Portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 3.webp",
      "/images/Portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 4.webp",
      "/images/Portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 5.webp",
      "/images/Portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 6.webp",
      "/images/Portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 7.webp",
      "/images/Portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 8.webp",
      "/images/Portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 9.webp",

    ],
    websiteUrl: "https://www.gpsvehicleinspections.com.au",
  },
  {
    id: "advanced-tree-lopping",
    name: "Advanced Tree Lopping",
    industry: "Tree Services",
    description: "Top tree care specialists in Sydney providing complete branding, web design, and arborist services for residential and commercial properties",
    services: ["Branding", "Web Design", "SEO"],
    image: "/images/Portfolio/Advanced Tree Lopping/Advanced tree looping.webp",
    images: [
      "/images/Portfolio/Advanced Tree Lopping/Advanced tree looping.webp",
      "/images/Portfolio/Advanced Tree Lopping/Advanced Tree Lopping 1.webp",
      "/images/Portfolio/Advanced Tree Lopping/Advanced Tree Lopping 2.webp",
      "/images/Portfolio/Advanced Tree Lopping/Advanced Tree Lopping 3.webp",
      "/images/Portfolio/Advanced Tree Lopping/Advanced Tree Lopping full page view.webp",
    ],
    websiteUrl: "https://advancedtreelopping.com.au",
  },
  {
    id: "adl99",
    name: "ADL99 - Advance Defense Layer",
    industry: "Cybersecurity",
    description: "Cybersecurity firm providing defensive technology solutions to protect organizations against digital threats and attacks",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/ADL99/ADL99.webp",
    images: ["/images/Portfolio/ADL99/ADL99.webp"],
    websiteUrl: "https://adl99.fractional-cmo.com.au",
  },
  {
    id: "demore-lending",
    name: "Demore Lending",
    industry: "Finance",
    description: "Professional lending services providing comprehensive mortgage and finance solutions",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/Demore Lending/Demore Lending.webp",
    images: ["/images/Portfolio/Demore Lending/Demore Lending.webp"],
    websiteUrl: "https://www.demorelending.com",
  },
  {
    id: "headway-abi-australia",
    name: "Headway ABI Australia",
    industry: "Disability Services",
    description: "Not-for-profit NDIS-registered organization delivering personalized support for individuals with acquired brain injuries",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/Headway ABI Australia/Headway ABI Australia.webp",
    images: ["/images/Portfolio/Headway ABI Australia/Headway ABI Australia.webp"],
    websiteUrl: "https://headwayabiaustralia.org",
  },
  {
    id: "vigilant-co-security",
    name: "Vigilant & Co Security Services",
    industry: "Security Services",
    description: "Comprehensive security solutions including corporate protection, event security, and 24/7 monitoring across Australia",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/VIgilat & Co/Vigilant & Co Security Services.webp",
    images: ["/images/Portfolio/VIgilat & Co/Vigilant & Co Security Services.webp"],
    websiteUrl: "https://vigilantsecurityservices.com.au",
  },
  {
    id: "actuate-property",
    name: "Actuate Property",
    industry: "Property Buyers Agent",
    description: "Modern website design with clean branding for Sydney's trusted property buyers agent",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/Actuate Property/Actuate Property.webp",
    images: ["/images/Portfolio/Actuate Property/Actuate Property.webp"],
    websiteUrl: "https://actuateproperty.com.au",
  },
  {
    id: "aj-engineering",
    name: "AJ Engineering Consultancy",
    industry: "Structural Engineering",
    description: "Structural, civil, and pre-purchase building inspection services specializing in residential and commercial assessments",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/AJ Engineering/AJ Engineering.webp",
    images: [
      "/images/Portfolio/AJ Engineering/AJ Engineering.webp",
      "/images/Portfolio/AJ Engineering/AJ Engineering 1.webp",
      "/images/Portfolio/AJ Engineering/AJ Engineering 2.webp",
      "/images/Portfolio/AJ Engineering/AJ Engineering 3.webp",
    ],
    websiteUrl: "https://www.ajengcon.com.au",
  },
  {
    id: "care-remedy",
    name: "Care Remedy Disability & Aged Care",
    industry: "NDIS & Aged Care",
    description: "Personalized disability and aged care services including in-home support and daily assistance in Sydney",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/Care Remedy/Care Remedy.webp",
    images: [
      "/images/Portfolio/Care Remedy/Care Remedy.webp",
      "/images/Portfolio/Care Remedy/Care Remedy 1.webp",
      "/images/Portfolio/Care Remedy/Care Remedy 2.webp",
      "/images/Portfolio/Care Remedy/Care Remedy 3.webp",
    ],
    websiteUrl: "https://www.careremedy.com.au",
  },
  {
    id: "zee-care",
    name: "Zee Care Disability & Aged Care",
    industry: "NDIS Provider",
    description: "Personalized support services including in-home care, disability accommodation, and respite care in Western Sydney",
    services: ["Web Design"],
    image: "/images/Portfolio/Zee Care/Zee Care Disability & Aged Care.webp",
    images: ["/images/Portfolio/Zee Care/Zee Care Disability & Aged Care.webp"],
    websiteUrl: "https://zeecare.com.au",
  },
  {
    id: "sync-support-care",
    name: "Sync Support Care",
    industry: "NDIS Support Services",
    description: "Personalized support services for individuals with disabilities including daily activities and community participation",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/Sync Support Care/Sync Support Care.webp",
    images: ["/images/Portfolio/Sync Support Care/Sync Support Care.webp"],
    websiteUrl: "https://syncsupportcare.com.au",
  },
  {
    id: "rmb-construction",
    name: "RMB Construction Pty Ltd",
    industry: "Custom Home Construction",
    description: "Architectural design and construction company specializing in custom homes, duplexes, and knockdown-rebuild projects",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/RMB Construction/RMB Construction Pty Ltd.webp",
    images: ["/images/Portfolio/RMB Construction/RMB Construction Pty Ltd.webp"],
    websiteUrl: "http://www.rmbconstructionsydney.com.au",
  },
  {
    id: "ui-disability-services",
    name: "U & I Disability Services",
    industry: "Disability & Aged Care",
    description: "Specialized support through NDIS services, aged care, and disability accommodation focusing on independence",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/U & I Disability/U & I Disability Services.webp",
    images: ["/images/Portfolio/U & I Disability/U & I Disability Services.webp"],
    websiteUrl: "https://unidisability.com.au",
  },
  {
    id: "mighty-steps",
    name: "Mighty Steps",
    industry: "Behavioral Therapy",
    description: "Evidence-based therapy including ABA, autism therapy, and early intervention for children ages 2-9",
    services: ["Web Design", "Branding", "Landing Pages"],
    image: "/images/Portfolio/Mighty Steps/Mighty Steps.webp",
    images: ["/images/Portfolio/Mighty Steps/Mighty Steps.webp"],
    websiteUrl: "https://therapy.mightysteps.com.au",
  },
  {
    id: "best-masonry",
    name: "Best Masonry",
    industry: "Bricklaying & Masonry",
    description: "Professional bricklaying services for residential and commercial projects including retaining walls",
    services: ["Web Design"],
    image: "/images/Portfolio/Best Masonry/Best Masonry.webp",
    images: ["/images/Portfolio/Best Masonry/Best Masonry.webp"],
    websiteUrl: "https://bestmasonry.com.au",
  },
  {
    id: "perth-carpet-steam-cleaners",
    name: "Perth Carpet Steam Cleaners",
    industry: "Cleaning Services",
    description: "Comprehensive cleaning solutions including carpet steam cleaning, upholstery restoration, and water damage services",
    services: ["Web Design", "SEO"],
    image: "/images/Portfolio/Perth Carpet Steam Cleaners/Perth Carpet Steam Cleaners.webp",
    images: ["/images/Portfolio/Perth Carpet Steam Cleaners/Perth Carpet Steam Cleaners.webp"],
    websiteUrl: "https://carpetscleaningperth.com.au",
  },
  {
    id: "polar-pest",
    name: "Polar Pest",
    industry: "Pest Control",
    description: "Comprehensive termite inspection, treatment, and prevention services backed by 15+ years of experience",
    services: ["Web Design"],
    image: "/images/Portfolio/Polar pest/Polar Pest.webp",
    images: ["/images/Portfolio/Polar pest/Polar Pest.webp"],
    websiteUrl: "https://termiteinspectionsydney.com",
  },
  {
    id: "satisfinance",
    name: "Satisfinance",
    industry: "Financial Services",
    description: "Professional branding and website for financial services provider",
    services: ["Branding", "Web Design"],
    image: "/images/Portfolio/Satisfinance/Satisfinance.webp",
    images: [
      "/images/Portfolio/Satisfinance/Satisfinance.webp",
      "/images/Portfolio/Satisfinance/Satisfinance 1.webp",
      "/images/Portfolio/Satisfinance/Satisfinance 2.webp",
      "/images/Portfolio/Satisfinance/Satisfinance 3.webp",
    ],
    websiteUrl: "https://satisfinance.com.au",
  },
  {
    id: "tente",
    name: "Tente",
    industry: "Industrial Equipment",
    description: "Industrial equipment website with SEO optimization for better visibility",
    services: ["Web Design", "SEO"],
    image: "/images/Portfolio/Tente/Tente.webp",
    images: ["/images/Portfolio/Tente/Tente.webp"],
    websiteUrl: "https://tente.com.au",
  },
  {
    id: "castor-master",
    name: "Castor Master",
    industry: "Industrial Equipment",
    description: "Complete digital solution with branding, website, SEO, and Google Ads",
    services: ["Branding", "Web Design", "SEO", "Google Ads"],
    image: "/images/Portfolio/Castor Master/Castor master.webp",
    images: [
      "/images/Portfolio/Castor Master/Castor master.webp",
      "/images/Portfolio/Castor Master/Castor master 1.webp",
      "/images/Portfolio/Castor Master/Castor master 2.webp",
      "/images/Portfolio/Castor Master/Castor Master 3.webp",
    ],
    websiteUrl: "https://castormaster.com.au",
  },
  {
    id: "two-brothers-removalist",
    name: "Two Brothers Removalist",
    industry: "Removalist Services",
    description: "SEO-optimized website driving leads for Sydney removalist services",
    services: ["Web Design", "SEO"],
    image: "/images/Portfolio/Two Brothers Removalist/Two Brothers Removalist.webp",
    images: ["/images/Portfolio/Two Brothers Removalist/Two Brothers Removalist.webp"],
    websiteUrl: "https://2brothersremovalist.com.au",
  },
  {
    id: "deepslice-pizza",
    name: "Deepslice Pizza",
    industry: "Food & Beverage",
    description: "Bold branding and web design for authentic pizza restaurant",
    services: ["Branding", "Web Design"],
    image: "/images/Portfolio/Deepslice Pizza/Deepslice Pizza.webp",
    images: [
      "/images/Portfolio/Deepslice Pizza/Deepslice Pizza.webp",
      "/images/Portfolio/Deepslice Pizza/Deepslice Pizza 1.webp",
      "/images/Portfolio/Deepslice Pizza/Deepslice Pizza 2.webp",
      "/images/Portfolio/Deepslice Pizza/Deepslice Pizza 3.webp",
    ],
    websiteUrl: "https://deepslicepizza.com.au",
  },
  {
    id: "the-tspoon-cafe",
    name: "The TSpoon Cafe",
    industry: "Food & Beverage",
    description: "Modern cafe website with online ordering and beautiful design showcasing menu items",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/The TSpoon Cafe/The Tspoon Cafe.webp",
    images: ["/images/Portfolio/The TSpoon Cafe/The Tspoon Cafe.webp"],
  },
  {
    id: "jabbs-excavations",
    name: "Jabbs Excavations",
    industry: "Excavation & Earthworks",
    description: "Premium excavation and earthworks company serving Sydney with professional demolition and site preparation services",
    services: ["Web Design", "Branding", "SEO"],
    image: "/images/Portfolio/Jabbs Excavations/Jabbs Excavations.webp",
    images: ["/images/Portfolio/Jabbs Excavations/Jabbs Excavations.webp"],
    websiteUrl: "http://jabbs.com.au/",
  },
  {
    id: "sydney-removalist",
    name: "Sydney Removalist",
    industry: "Moving & Relocation",
    description: "Trusted moving company offering residential, commercial relocations, and storage with 15+ years experience",
    services: ["Web Design", "SEO"],
    image: "/images/Portfolio/Sydney Removalist/Sydney Removalist.webp",
    images: ["/images/Portfolio/Sydney Removalist/Sydney Removalist.webp"],
    websiteUrl: "https://www.sydneyremovalist.com.au",
  },
  {
    id: "removalist-sydney",
    name: "Removalist Sydney",
    industry: "Moving & Relocation",
    description: "Professional removalist services for Sydney homes and businesses with reliable moving solutions",
    services: ["Web Design", "SEO"],
    image: "/images/Portfolio/Removalist Sydney/Removalist Sydney.webp",
    images: [
      "/images/Portfolio/Removalist Sydney/Removalist Sydney.webp",
      "/images/Portfolio/Removalist Sydney/Removalist Sydney 1.webp",
      "/images/Portfolio/Removalist Sydney/Removalist Sydney 2.webp",
      "/images/Portfolio/Removalist Sydney/Removalist Sydney 3.webp",
      "/images/Portfolio/Removalist Sydney/Removalist Sydney 4.webp",
      "/images/Portfolio/Removalist Sydney/Removalist Sydney 5.webp",
      "/images/Portfolio/Removalist Sydney/Removalist Sydney 6.webp",
      "/images/Portfolio/Removalist Sydney/Removalist Sydney 7.webp",
      "/images/Portfolio/Removalist Sydney/Removalist Sydney 8.webp",
    ],
  },
  {
    id: "ace-build",
    name: "Ace Build",
    industry: "Construction",
    description: "Professional building and construction services with quality craftsmanship",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/Ace Build/Ace Build.webp",
    images: [
      "/images/Portfolio/Ace Build/Ace Build.webp",
      "/images/Portfolio/Ace Build/Web Design for Builder.webp",
    ],
  },
  {
    id: "anthonys-painting",
    name: "Anthonys Painting",
    industry: "Painting Services",
    description: "Professional painting services for residential and commercial properties",
    services: ["Web Design"],
    image: "/images/Portfolio/Anthonys Painting/Anthonys Painting.webp",
    images: ["/images/Portfolio/Anthonys Painting/Anthonys Painting.webp"],
  },
  {
    id: "better-skin-care",
    name: "Better Skin Care",
    industry: "Healthcare & Beauty",
    description: "Professional skincare clinic offering advanced treatments and consultations",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/Better Skin Care/Better Skin Care.webp",
    images: [
      "/images/Portfolio/Better Skin Care/Better Skin Care.webp",
      "/images/Portfolio/Better Skin Care/Better Skin Care all pages.webp",
    ],
  },
  {
    id: "blinds-sydney",
    name: "Blinds Sydney",
    industry: "Home Furnishings",
    description: "Quality window blinds and shutters for Sydney homes and businesses",
    services: ["Web Design", "SEO"],
    image: "/images/Portfolio/Blinds Sydney/Blinds Sydney.webp",
    images: [
      "/images/Portfolio/Blinds Sydney/Blinds Sydney.webp",
      "/images/Portfolio/Blinds Sydney/Blinds Sydney 1.webp",
      "/images/Portfolio/Blinds Sydney/Blinds Sydney 2.webp",
      "/images/Portfolio/Blinds Sydney/Blinds Sydney 3.webp",
    ],
  },
  {
    id: "bricklayers-sydney",
    name: "Bricklayers Sydney",
    industry: "Bricklaying",
    description: "Expert bricklaying services for new construction and restoration projects",
    services: ["Web Design", "SEO"],
    image: "/images/Portfolio/Bricklayers Sydney/Bricklayers Sydney.webp",
    images: [
      "/images/Portfolio/Bricklayers Sydney/Bricklayers Sydney.webp",
      "/images/Portfolio/Bricklayers Sydney/Bricklayers Sydney 1.webp",
      "/images/Portfolio/Bricklayers Sydney/Bricklayers Sydney 2.webp",
      "/images/Portfolio/Bricklayers Sydney/Bricklayers Sydney 3.webp",
    ],
  },
  {
    id: "builders-sydney",
    name: "Builders Sydney",
    industry: "Construction",
    description: "Premium building services for residential and commercial construction projects",
    services: ["Web Design", "SEO"],
    image: "/images/Portfolio/Builders Sydney/Builders Sydney.webp",
    images: [
      "/images/Portfolio/Builders Sydney/Builders Sydney.webp",
      "/images/Portfolio/Builders Sydney/Builders Sydney 1.webp",
      "/images/Portfolio/Builders Sydney/Builders Sydney 2.webp",
      "/images/Portfolio/Builders Sydney/Builders Sydney 3.webp",
    ],
  },
  {
    id: "comfort-disability-services",
    name: "Comfort Disability Services",
    industry: "NDIS Provider",
    description: "Compassionate disability support services focused on independence and quality of life",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/Comfort Disability Services/Comfort Disability Services.webp",
    images: ["/images/Portfolio/Comfort Disability Services/Comfort Disability Services.webp"],
  },
  {
    id: "excavation-sydney",
    name: "Excavation Sydney",
    industry: "Excavation",
    description: "Professional excavation services for residential and commercial projects",
    services: ["Web Design", "SEO"],
    image: "/images/Portfolio/Excavation Sydney/Excavation Sydney.webp",
    images: [
      "/images/Portfolio/Excavation Sydney/Excavation Sydney.webp",
      "/images/Portfolio/Excavation Sydney/Excavation Sydney 1.webp",
      "/images/Portfolio/Excavation Sydney/Excavation Sydney 2.webp",
      "/images/Portfolio/Excavation Sydney/Excavation Sydney 3.webp",
      "/images/Portfolio/Excavation Sydney/Excavation Sydney 4.webp",
    ],
  },
  {
    id: "jose-journeys",
    name: "Jose Journeys",
    industry: "NDIS Provider",
    description: "Personalized travel experiences and tour packages for adventure seekers",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/Jose Journeys/Jose Journeys.webp",
    images: [
      "/images/Portfolio/Jose Journeys/Jose Journeys.webp",
      "/images/Portfolio/Jose Journeys/Jose Journeys 1.webp",
      "/images/Portfolio/Jose Journeys/Jose Journeys 2.webp",
      "/images/Portfolio/Jose Journeys/Jose Journeys 3.webp",
    ],
  },
  {
    id: "marsden-therapy",
    name: "Marsden Therapy",
    industry: "Healthcare",
    description: "Professional therapy services with experienced practitioners",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/Marsden Therapy/Marsden Therapy.webp",
    images: [
      "/images/Portfolio/Marsden Therapy/Marsden Therapy.webp",
      "/images/Portfolio/Marsden Therapy/Marsden Therapy Website Responsive in all Devices.webp",
    ],
  },
  {
    id: "ndis-service-providers",
    name: "NDIS Service Providers",
    industry: "NDIS Provider",
    description: "Comprehensive NDIS services connecting participants with quality providers",
    services: ["Web Design"],
    image: "/images/Portfolio/NDIS Service Providers/NDIS Service Providers.webp",
    images: ["/images/Portfolio/NDIS Service Providers/NDIS Service Providers.webp"],
  },
  {
    id: "out-wood-home-improvements",
    name: "Out Wood Home Improvements",
    industry: "Home Improvement",
    description: "Quality home improvement and renovation services for Sydney homes",
    services: ["Web Design"],
    image: "/images/Portfolio/Out Wood Home Improvements/Out Wood Home Improvements.webp",
    images: ["/images/Portfolio/Out Wood Home Improvements/Out Wood Home Improvements.webp"],
  },
  {
    id: "pineapple-funding",
    name: "Pineapple Funding",
    industry: "Finance",
    description: "Innovative funding solutions for businesses and individuals",
    services: ["Web Design", "Branding"],
    image: "/images/Portfolio/Pineapple Funding/Pineapple Funding.webp",
    images: [
      "/images/Portfolio/Pineapple Funding/Pineapple Funding.webp",
      "/images/Portfolio/Pineapple Funding/Pineapple Funding 1.webp",
      "/images/Portfolio/Pineapple Funding/Pineapple Funding 2.webp",
      "/images/Portfolio/Pineapple Funding/Pineapple Funding 3.webp",
    ],
  },
  {
    id: "showfreight",
    name: "Showfreight",
    industry: "Logistics",
    description: "Professional freight and logistics services for exhibitions and events",
    services: ["Web Design"],
    image: "/images/Portfolio/Showfreight/Showfreight.webp",
    images: ["/images/Portfolio/Showfreight/Showfreight.webp"],
  },
  {
    id: "south-pacific-aromas",
    name: "South Pacific Aromas",
    industry: "Essential Oils",
    description: "Premium essential oils and aromatherapy products from the South Pacific",
    services: ["Web Design", "E-commerce"],
    image: "/images/Portfolio/South Pacific Aromas/South Pacific Aromas.webp",
    images: ["/images/Portfolio/South Pacific Aromas/South Pacific Aromas.webp"],
  },
  {
    id: "ts-road-works",
    name: "T&S Road Works",
    industry: "Civil Construction",
    description: "Professional road construction and maintenance services",
    services: ["Web Design"],
    image: "/images/Portfolio/T&S Road Works/T & S Roadworks.webp",
    images: ["/images/Portfolio/T&S Road Works/T & S Roadworks.webp"],
  },
  {
    id: "takeaway-packaging",
    name: "Takeaway Packaging",
    industry: "Packaging Solutions",
    description: "Eco-friendly takeaway packaging solutions for restaurants and cafes",
    services: ["Web Design", "E-commerce"],
    image: "/images/Portfolio/Takeaway Packaging/Takeaway Packaging.webp",
    images: [
      "/images/Portfolio/Takeaway Packaging/Takeaway Packaging.webp",
      "/images/Portfolio/Takeaway Packaging/Takeaway Packaging 1.webp",
      "/images/Portfolio/Takeaway Packaging/Takeaway Packaging 2.webp",
      "/images/Portfolio/Takeaway Packaging/Takeaway Packaging 3.webp",
      "/images/Portfolio/Takeaway Packaging/Takeaway Packaging 4.webp",
    ],
  },
  // Landing Page Templates
  {
    id: "landing-page-template-1",
    name: "Landing Page Template 1",
    industry: "Template",
    description: "Modern, conversion-optimized landing page template with clean design and strategic CTAs",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 1/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 1/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 1/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 1/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 1/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 1/5.png",
    ],
  },
  {
    id: "landing-page-template-2",
    name: "Landing Page Template 2",
    industry: "Template",
    description: "Professional landing page design with compelling hero section and social proof elements",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 2/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 2/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 2/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 2/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 2/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 2/5.png",
    ],
  },
  {
    id: "landing-page-template-3",
    name: "Landing Page Template 3",
    industry: "Template",
    description: "High-converting landing page template featuring bold visuals and clear value propositions",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 3/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 3/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 3/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 3/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 3/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 3/5.png",
    ],
  },
  {
    id: "landing-page-template-4",
    name: "Landing Page Template 4",
    industry: "Template",
    description: "Sleek landing page design with engaging animations and mobile-first approach",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 4/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 4/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 4/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 4/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 4/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 4/5.png",
    ],
  },
  {
    id: "landing-page-template-5",
    name: "Landing Page Template 5",
    industry: "Template",
    description: "Conversion-focused landing page with testimonials and trust badges for maximum credibility",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 5/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 5/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 5/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 5/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 5/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 5/5.png",
    ],
  },
  {
    id: "landing-page-template-6",
    name: "Landing Page Template 6",
    industry: "Template",
    description: "Dynamic landing page template with interactive elements and video backgrounds",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 6/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 6/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 6/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 6/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 6/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 6/5.png",
    ],
  },
  {
    id: "landing-page-template-7",
    name: "Landing Page Template 7",
    industry: "Template",
    description: "Minimalist landing page design emphasizing clarity and user experience",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 7/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 7/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 7/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 7/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 7/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 7/5.png",
    ],
  },
  {
    id: "landing-page-template-8",
    name: "Landing Page Template 8",
    industry: "Template",
    description: "Bold and colorful landing page template perfect for creative businesses",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 8/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 8/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 8/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 8/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 8/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 8/5.png",
    ],
  },
  {
    id: "landing-page-template-9",
    name: "Landing Page Template 9",
    industry: "Template",
    description: "Professional corporate landing page with clean layout and data visualization",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 9/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 9/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 9/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 9/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 9/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 9/5.png",
    ],
  },
  {
    id: "landing-page-template-10",
    name: "Landing Page Template 10",
    industry: "Template",
    description: "Modern landing page with parallax scrolling and micro-interactions",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 10/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 10/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 10/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 10/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 10/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 10/5.png",
    ],
  },
  {
    id: "landing-page-template-11",
    name: "Landing Page Template 11",
    industry: "Template",
    description: "High-impact landing page design with strategic whitespace and premium feel",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 11/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 11/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 11/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 11/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 11/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 11/5.png",
    ],
  },
  {
    id: "landing-page-template-12",
    name: "Landing Page Template 12",
    industry: "Template",
    description: "Engaging landing page template with storytelling elements and customer journey focus",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 12/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 12/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 12/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 12/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 12/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 12/5.png",
    ],
  },
  {
    id: "landing-page-template-13",
    name: "Landing Page Template 13",
    industry: "Template",
    description: "Conversion-optimized landing page featuring comparison tables and feature highlights",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 13/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 13/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 13/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 13/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 13/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 13/5.png",
    ],
  },
  {
    id: "landing-page-template-14",
    name: "Landing Page Template 14",
    industry: "Template",
    description: "Contemporary landing page design with gradient backgrounds and modern typography",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 14/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 14/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 14/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 14/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 14/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 14/5.png",
    ],
  },
  {
    id: "landing-page-template-15",
    name: "Landing Page Template 15",
    industry: "Template",
    description: "SaaS-focused landing page with pricing tiers and feature breakdown",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 15/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 15/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 15/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 15/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 15/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 15/5.png",
    ],
  },
  {
    id: "landing-page-template-16",
    name: "Landing Page Template 16",
    industry: "Template",
    description: "Event landing page template with countdown timer and registration forms",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 16/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 16/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 16/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 16/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 16/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 16/5.png",
    ],
  },
  {
    id: "landing-page-template-17",
    name: "Landing Page Template 17",
    industry: "Template",
    description: "App showcase landing page with device mockups and feature demonstrations",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 17/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 17/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 17/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 17/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 17/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 17/5.png",
    ],
  },
  {
    id: "landing-page-template-18",
    name: "Landing Page Template 18",
    industry: "Template",
    description: "Lead generation landing page with multi-step form and progress indicators",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 18/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 18/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 18/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 18/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 18/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 18/5.png",
    ],
  },
  {
    id: "landing-page-template-19",
    name: "Landing Page Template 19",
    industry: "Template",
    description: "Product launch landing page with animated product reveals and pre-order functionality",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 19/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 19/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 19/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 19/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 19/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 19/5.png",
    ],
  },
  {
    id: "landing-page-template-20",
    name: "Landing Page Template 20",
    industry: "Template",
    description: "Service-based landing page with before/after galleries and client testimonials",
    services: ["Landing Pages", "Web Design"],
    image: "/images/Portfolio/Landing Page Template/Landing Page Template - 20/1.png",
    images: [
      "/images/Portfolio/Landing Page Template/Landing Page Template - 20/1.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 20/2.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 20/3.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 20/4.png",
      "/images/Portfolio/Landing Page Template/Landing Page Template - 20/5.png",
    ],
  },
];
