// Portfolio data generated from /public/images/portfolio folders
export interface PortfolioItem {
  id: string;
  name: string;
  industry: string;
  description: string;
  services: string[];
  image: string;
  images: string[];
  websiteUrl?: string;
}

export const portfolioData: PortfolioItem[] = [
  {
    id: "six-brothers-removalists",
    name: "Six Brothers Removalists",
    industry: "Moving & Relocation",
    description: "One of Australia's top removalist companies providing professional residential and commercial moving services across Sydney and NSW",
    services: ["Web Design", "SEO", "Google Ads", "Branding"],
    image: "/images/portfolio/Six Brothers Removalists/Six Brothers Removalist.webp",
    images: [
      "/images/portfolio/Six Brothers Removalists/Six Brothers Removalist.webp",
      "/images/portfolio/Six Brothers Removalists/Web design for Removalist.webp",
    ],
    websiteUrl: "https://www.sixbrothersremovalist.com.au/",
  },
  {
    id: "osan-ability",
    name: "OSAN Ability",
    industry: "NDIS Provider",
    description: "Leading NDIS provider offering comprehensive disability support services including full-service digital marketing: branding, website, SEO, and advertising",
    services: ["Branding", "Web Design", "Google Ads", "SEO", "Social Media"],
    image: "/images/portfolio/OSAN Ability/OSAN Ability.webp",
    images: [
      "/images/portfolio/OSAN Ability/OSAN Ability.webp",
      "/images/portfolio/OSAN Ability/OSAN Ability 1.webp",
      "/images/portfolio/OSAN Ability/OSAN Ability 2.webp",
      "/images/portfolio/OSAN Ability/OSAN Ability 3.webp",
      "/images/portfolio/OSAN Ability/OSAN Ability 4.webp",
      "/images/portfolio/OSAN Ability/OSAN Ability 5.webp",
    ],
    websiteUrl: "https://www.osanability.com.au/",
  },
  {
    id: "gps-vehicle-inspections",
    name: "GPS Vehicle Inspections",
    industry: "Automotive Inspection",
    description: "Mobile pre-purchase vehicle inspection services with experienced mechanics delivering comprehensive reports within 24 hours",
    services: ["Branding", "Web Design", "SEO", "Google Ads", "Social Media"],
    image: "/images/portfolio/GPS Vehicle Inspections/GPS Vehicle inspection.webp",
    images: [
      "/images/portfolio/GPS Vehicle Inspections/GPS Vehicle inspection.webp",
      "/images/portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 1.webp",
      "/images/portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 2.webp",
      "/images/portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 3.webp",
      "/images/portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 4.webp",
      "/images/portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 5.webp",
      "/images/portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 6.webp",
      "/images/portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 7.webp",
      "/images/portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 8.webp",
      "/images/portfolio/GPS Vehicle Inspections/GPS Vehicle inspection 9.webp",
      
    ],
    websiteUrl: "https://www.gpsvehicleinspections.com.au",
  },
  {
    id: "advanced-tree-lopping",
    name: "Advanced Tree Lopping",
    industry: "Tree Services",
    description: "Top tree care specialists in Sydney providing complete branding, web design, and arborist services for residential and commercial properties",
    services: ["Branding", "Web Design", "SEO"],
    image: "/images/portfolio/Advanced Tree Lopping/Advanced tree looping.webp",
    images: [
      "/images/portfolio/Advanced Tree Lopping/Advanced tree looping.webp",
      "/images/portfolio/Advanced Tree Lopping/Advanced Tree Lopping 1.webp",
      "/images/portfolio/Advanced Tree Lopping/Advanced Tree Lopping 2.webp",
      "/images/portfolio/Advanced Tree Lopping/Advanced Tree Lopping 3.webp",
      "/images/portfolio/Advanced Tree Lopping/Advanced Tree Lopping full page view.webp",
    ],
    websiteUrl: "https://advancedtreelopping.com.au",
  },
  {
    id: "adl99",
    name: "ADL99 - Advance Defense Layer",
    industry: "Cybersecurity",
    description: "Cybersecurity firm providing defensive technology solutions to protect organizations against digital threats and attacks",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/ADL99/ADL99.webp",
    images: ["/images/portfolio/ADL99/ADL99.webp"],
    websiteUrl: "https://adl99.fractional-cmo.com.au",
  },
  {
    id: "demore-lending",
    name: "Demore Lending",
    industry: "Finance",
    description: "Professional lending services providing comprehensive mortgage and finance solutions",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/Demore Lending/Demore Lending.webp",
    images: ["/images/portfolio/Demore Lending/Demore Lending.webp"],
    websiteUrl: "https://www.demorelending.com",
  },
  {
    id: "headway-abi-australia",
    name: "Headway ABI Australia",
    industry: "Disability Services",
    description: "Not-for-profit NDIS-registered organization delivering personalized support for individuals with acquired brain injuries",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/Headway ABI Australia/Headway ABI Australia.webp",
    images: ["/images/portfolio/Headway ABI Australia/Headway ABI Australia.webp"],
    websiteUrl: "https://headwayabiaustralia.org",
  },
  {
    id: "vigilant-co-security",
    name: "Vigilant & Co Security Services",
    industry: "Security Services",
    description: "Comprehensive security solutions including corporate protection, event security, and 24/7 monitoring across Australia",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/VIgilat & Co/Vigilant & Co Security Services.webp",
    images: ["/images/portfolio/VIgilat & Co/Vigilant & Co Security Services.webp"],
    websiteUrl: "https://vigilantsecurityservices.com.au",
  },
  {
    id: "actuate-property",
    name: "Actuate Property",
    industry: "Property Buyers Agent",
    description: "Modern website design with clean branding for Sydney's trusted property buyers agent",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/Actuate Property/Actuate Property.webp",
    images: ["/images/portfolio/Actuate Property/Actuate Property.webp"],
    websiteUrl: "https://actuateproperty.com.au",
  },
  {
    id: "aj-engineering",
    name: "AJ Engineering Consultancy",
    industry: "Structural Engineering",
    description: "Structural, civil, and pre-purchase building inspection services specializing in residential and commercial assessments",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/AJ Engineering/AJ Engineering.webp",
    images: [
      "/images/portfolio/AJ Engineering/AJ Engineering.webp",
      "/images/portfolio/AJ Engineering/AJ Engineering 1.webp",
      "/images/portfolio/AJ Engineering/AJ Engineering 2.webp",
      "/images/portfolio/AJ Engineering/AJ Engineering 3.webp",
    ],
    websiteUrl: "https://www.ajengcon.com.au",
  },
  {
    id: "care-remedy",
    name: "Care Remedy Disability & Aged Care",
    industry: "NDIS & Aged Care",
    description: "Personalized disability and aged care services including in-home support and daily assistance in Sydney",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/Care Remedy/Care Remedy.webp",
    images: [
      "/images/portfolio/Care Remedy/Care Remedy.webp",
      "/images/portfolio/Care Remedy/Care Remedy 1.webp",
      "/images/portfolio/Care Remedy/Care Remedy 2.webp",
      "/images/portfolio/Care Remedy/Care Remedy 3.webp",
    ],
    websiteUrl: "https://www.careremedy.com.au",
  },
  {
    id: "zee-care",
    name: "Zee Care Disability & Aged Care",
    industry: "NDIS Provider",
    description: "Personalized support services including in-home care, disability accommodation, and respite care in Western Sydney",
    services: ["Web Design"],
    image: "/images/portfolio/Zee Care/Zee Care Disability & Aged Care.webp",
    images: ["/images/portfolio/Zee Care/Zee Care Disability & Aged Care.webp"],
    websiteUrl: "https://zeecare.com.au",
  },
  {
    id: "sync-support-care",
    name: "Sync Support Care",
    industry: "NDIS Support Services",
    description: "Personalized support services for individuals with disabilities including daily activities and community participation",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/Sync Support Care/Sync Support Care.webp",
    images: ["/images/portfolio/Sync Support Care/Sync Support Care.webp"],
    websiteUrl: "https://syncsupportcare.com.au",
  },
  {
    id: "rmb-construction",
    name: "RMB Construction Pty Ltd",
    industry: "Custom Home Construction",
    description: "Architectural design and construction company specializing in custom homes, duplexes, and knockdown-rebuild projects",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/RMB Construction/RMB Construction Pty Ltd.webp",
    images: ["/images/portfolio/RMB Construction/RMB Construction Pty Ltd.webp"],
    websiteUrl: "http://www.rmbconstructionsydney.com.au",
  },
  {
    id: "ui-disability-services",
    name: "U & I Disability Services",
    industry: "Disability & Aged Care",
    description: "Specialized support through NDIS services, aged care, and disability accommodation focusing on independence",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/U & I Disability/U & I Disability Services.webp",
    images: ["/images/portfolio/U & I Disability/U & I Disability Services.webp"],
    websiteUrl: "https://unidisability.com.au",
  },
  {
    id: "mighty-steps",
    name: "Mighty Steps",
    industry: "Behavioral Therapy",
    description: "Evidence-based therapy including ABA, autism therapy, and early intervention for children ages 2-9",
    services: ["Web Design", "Branding", "Landing Pages"],
    image: "/images/portfolio/Mighty Steps/Mighty Steps.webp",
    images: ["/images/portfolio/Mighty Steps/Mighty Steps.webp"],
    websiteUrl: "https://therapy.mightysteps.com.au",
  },
  {
    id: "best-masonry",
    name: "Best Masonry",
    industry: "Bricklaying & Masonry",
    description: "Professional bricklaying services for residential and commercial projects including retaining walls",
    services: ["Web Design"],
    image: "/images/portfolio/Best Masonry/Best Masonry.webp",
    images: ["/images/portfolio/Best Masonry/Best Masonry.webp"],
    websiteUrl: "https://bestmasonry.com.au",
  },
  {
    id: "perth-carpet-steam-cleaners",
    name: "Perth Carpet Steam Cleaners",
    industry: "Cleaning Services",
    description: "Comprehensive cleaning solutions including carpet steam cleaning, upholstery restoration, and water damage services",
    services: ["Web Design", "SEO"],
    image: "/images/portfolio/Perth Carpet Steam Cleaners/Perth Carpet Steam Cleaners.webp",
    images: ["/images/portfolio/Perth Carpet Steam Cleaners/Perth Carpet Steam Cleaners.webp"],
    websiteUrl: "https://carpetscleaningperth.com.au",
  },
  {
    id: "polar-pest",
    name: "Polar Pest",
    industry: "Pest Control",
    description: "Comprehensive termite inspection, treatment, and prevention services backed by 15+ years of experience",
    services: ["Web Design"],
    image: "/images/portfolio/Polar pest/Polar Pest.webp",
    images: ["/images/portfolio/Polar pest/Polar Pest.webp"],
    websiteUrl: "https://termiteinspectionsydney.com",
  },
  {
    id: "satisfinance",
    name: "Satisfinance",
    industry: "Financial Services",
    description: "Professional branding and website for financial services provider",
    services: ["Branding", "Web Design"],
    image: "/images/portfolio/Satisfinance/Satisfinance.webp",
    images: [
      "/images/portfolio/Satisfinance/Satisfinance.webp",
      "/images/portfolio/Satisfinance/Satisfinance 1.webp",
      "/images/portfolio/Satisfinance/Satisfinance 2.webp",
      "/images/portfolio/Satisfinance/Satisfinance 3.webp",
    ],
    websiteUrl: "https://satisfinance.com.au",
  },
  {
    id: "tente",
    name: "Tente",
    industry: "Industrial Equipment",
    description: "Industrial equipment website with SEO optimization for better visibility",
    services: ["Web Design", "SEO"],
    image: "/images/portfolio/Tente/Tente.webp",
    images: ["/images/portfolio/Tente/Tente.webp"],
    websiteUrl: "https://tente.com.au",
  },
  {
    id: "castor-master",
    name: "Castor Master",
    industry: "Industrial Equipment",
    description: "Complete digital solution with branding, website, SEO, and Google Ads",
    services: ["Branding", "Web Design", "SEO", "Google Ads"],
    image: "/images/portfolio/Castor Master/Castor master.webp",
    images: [
      "/images/portfolio/Castor Master/Castor master.webp",
      "/images/portfolio/Castor Master/Castor master 1.webp",
      "/images/portfolio/Castor Master/Castor master 2.webp",
      "/images/portfolio/Castor Master/Castor Master 3.webp",
    ],
    websiteUrl: "https://castormaster.com.au",
  },
  {
    id: "two-brothers-removalist",
    name: "Two Brothers Removalist",
    industry: "Removalist Services",
    description: "SEO-optimized website driving leads for Sydney removalist services",
    services: ["Web Design", "SEO"],
    image: "/images/portfolio/Two Brothers Removalist/Two Brothers Removalist.webp",
    images: ["/images/portfolio/Two Brothers Removalist/Two Brothers Removalist.webp"],
    websiteUrl: "https://2brothersremovalist.com.au",
  },
  {
    id: "deepslice-pizza",
    name: "Deepslice Pizza",
    industry: "Hospitality",
    description: "Bold branding and web design for authentic pizza restaurant",
    services: ["Branding", "Web Design"],
    image: "/images/portfolio/Deepslice Pizza/Deepslice Pizza.webp",
    images: [
      "/images/portfolio/Deepslice Pizza/Deepslice Pizza.webp",
      "/images/portfolio/Deepslice Pizza/Deepslice Pizza 1.webp",
      "/images/portfolio/Deepslice Pizza/Deepslice Pizza 2.webp",
      "/images/portfolio/Deepslice Pizza/Deepslice Pizza 3.webp",
    ],
    websiteUrl: "https://deepslicepizza.com.au",
  },
  {
    id: "the-tspoon-cafe",
    name: "The TSpoon Cafe",
    industry: "Hospitality",
    description: "Modern cafe website with online ordering and beautiful design showcasing menu items",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/The TSpoon Cafe/The Tspoon Cafe.webp",
    images: ["/images/portfolio/The TSpoon Cafe/The Tspoon Cafe.webp"],
  },
  {
    id: "jabbs-excavations",
    name: "Jabbs Excavations",
    industry: "Excavation & Earthworks",
    description: "Premium excavation and earthworks company serving Sydney with professional demolition and site preparation services",
    services: ["Web Design", "Branding", "SEO"],
    image: "/images/portfolio/Jabbs Excavations/Jabbs Excavations.webp",
    images: ["/images/portfolio/Jabbs Excavations/Jabbs Excavations.webp"],
    websiteUrl: "http://jabbs.com.au/",
  },
  {
    id: "sydney-removalist",
    name: "Sydney Removalist",
    industry: "Moving & Relocation",
    description: "Trusted moving company offering residential, commercial relocations, and storage with 15+ years experience",
    services: ["Web Design", "SEO"],
    image: "/images/portfolio/Sydney Removalist/Sydney Removalist.webp",
    images: ["/images/portfolio/Sydney Removalist/Sydney Removalist.webp"],
    websiteUrl: "https://www.sydneyremovalist.com.au",
  },
  {
    id: "removalist-sydney",
    name: "Removalist Sydney",
    industry: "Moving & Relocation",
    description: "Professional removalist services for Sydney homes and businesses with reliable moving solutions",
    services: ["Web Design", "SEO"],
    image: "/images/portfolio/Removalist Sydney/Removalist Sydney.webp",
    images: [
      "/images/portfolio/Removalist Sydney/Removalist Sydney.webp",
      "/images/portfolio/Removalist Sydney/Removalist Sydney 1.webp",
      "/images/portfolio/Removalist Sydney/Removalist Sydney 2.webp",
      "/images/portfolio/Removalist Sydney/Removalist Sydney 3.webp",
      "/images/portfolio/Removalist Sydney/Removalist Sydney 4.webp",
      "/images/portfolio/Removalist Sydney/Removalist Sydney 5.webp",
      "/images/portfolio/Removalist Sydney/Removalist Sydney 6.webp",
      "/images/portfolio/Removalist Sydney/Removalist Sydney 7.webp",
      "/images/portfolio/Removalist Sydney/Removalist Sydney 8.webp",
    ],
  },
  {
    id: "ace-build",
    name: "Ace Build",
    industry: "Construction",
    description: "Professional building and construction services with quality craftsmanship",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/Ace Build/Ace Build.webp",
    images: [
      "/images/portfolio/Ace Build/Ace Build.webp",
      "/images/portfolio/Ace Build/Web Design for Builder.webp",
    ],
  },
  {
    id: "anthonys-painting",
    name: "Anthonys Painting",
    industry: "Painting Services",
    description: "Professional painting services for residential and commercial properties",
    services: ["Web Design"],
    image: "/images/portfolio/Anthonys Painting/Anthonys Painting.webp",
    images: ["/images/portfolio/Anthonys Painting/Anthonys Painting.webp"],
  },
  {
    id: "better-skin-care",
    name: "Better Skin Care",
    industry: "Healthcare & Beauty",
    description: "Professional skincare clinic offering advanced treatments and consultations",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/Better Skin Care/Better Skin Care.webp",
    images: [
      "/images/portfolio/Better Skin Care/Better Skin Care.webp",
      "/images/portfolio/Better Skin Care/Better Skin Care all pages.webp",
    ],
  },
  {
    id: "blinds-sydney",
    name: "Blinds Sydney",
    industry: "Home Furnishings",
    description: "Quality window blinds and shutters for Sydney homes and businesses",
    services: ["Web Design", "SEO"],
    image: "/images/portfolio/Blinds Sydney/Blinds Sydney.webp",
    images: [
      "/images/portfolio/Blinds Sydney/Blinds Sydney.webp",
      "/images/portfolio/Blinds Sydney/Blinds Sydney 1.webp",
      "/images/portfolio/Blinds Sydney/Blinds Sydney 2.webp",
      "/images/portfolio/Blinds Sydney/Blinds Sydney 3.webp",
    ],
  },
  {
    id: "bricklayers-sydney",
    name: "Bricklayers Sydney",
    industry: "Bricklaying",
    description: "Expert bricklaying services for new construction and restoration projects",
    services: ["Web Design", "SEO"],
    image: "/images/portfolio/Bricklayers Sydney/Bricklayers Sydney.webp",
    images: [
      "/images/portfolio/Bricklayers Sydney/Bricklayers Sydney.webp",
      "/images/portfolio/Bricklayers Sydney/Bricklayers Sydney 1.webp",
      "/images/portfolio/Bricklayers Sydney/Bricklayers Sydney 2.webp",
      "/images/portfolio/Bricklayers Sydney/Bricklayers Sydney 3.webp",
    ],
  },
  {
    id: "builders-sydney",
    name: "Builders Sydney",
    industry: "Construction",
    description: "Premium building services for residential and commercial construction projects",
    services: ["Web Design", "SEO"],
    image: "/images/portfolio/Builders Sydney/Builders Sydney.webp",
    images: [
      "/images/portfolio/Builders Sydney/Builders Sydney.webp",
      "/images/portfolio/Builders Sydney/Builders Sydney 1.webp",
      "/images/portfolio/Builders Sydney/Builders Sydney 2.webp",
      "/images/portfolio/Builders Sydney/Builders Sydney 3.webp",
    ],
  },
  {
    id: "comfort-disability-services",
    name: "Comfort Disability Services",
    industry: "NDIS Provider",
    description: "Compassionate disability support services focused on independence and quality of life",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/Comfort Disability Services/Comfort Disability Services.webp",
    images: ["/images/portfolio/Comfort Disability Services/Comfort Disability Services.webp"],
  },
  {
    id: "excavation-sydney",
    name: "Excavation Sydney",
    industry: "Excavation",
    description: "Professional excavation services for residential and commercial projects",
    services: ["Web Design", "SEO"],
    image: "/images/portfolio/Excavation Sydney/Excavation Sydney.webp",
    images: [
      "/images/portfolio/Excavation Sydney/Excavation Sydney.webp",
      "/images/portfolio/Excavation Sydney/Excavation Sydney 1.webp",
      "/images/portfolio/Excavation Sydney/Excavation Sydney 2.webp",
      "/images/portfolio/Excavation Sydney/Excavation Sydney 3.webp",
      "/images/portfolio/Excavation Sydney/Excavation Sydney 4.webp",
    ],
  },
  {
    id: "jose-journeys",
    name: "Jose Journeys",
    industry: "Travel & Tourism",
    description: "Personalized travel experiences and tour packages for adventure seekers",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/Jose Journeys/Jose Journeys.webp",
    images: [
      "/images/portfolio/Jose Journeys/Jose Journeys.webp",
      "/images/portfolio/Jose Journeys/Jose Journeys 1.webp",
      "/images/portfolio/Jose Journeys/Jose Journeys 2.webp",
      "/images/portfolio/Jose Journeys/Jose Journeys 3.webp",
    ],
  },
  {
    id: "marsden-therapy",
    name: "Marsden Therapy",
    industry: "Healthcare",
    description: "Professional therapy services with experienced practitioners",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/Marsden Therapy/Marsden Therapy.webp",
    images: [
      "/images/portfolio/Marsden Therapy/Marsden Therapy.webp",
      "/images/portfolio/Marsden Therapy/Marsden Therapy Website Responsive in all Devices.webp",
    ],
  },
  {
    id: "ndis-service-providers",
    name: "NDIS Service Providers",
    industry: "NDIS Provider",
    description: "Comprehensive NDIS services connecting participants with quality providers",
    services: ["Web Design"],
    image: "/images/portfolio/NDIS Service Providers/NDIS Service Providers.webp",
    images: ["/images/portfolio/NDIS Service Providers/NDIS Service Providers.webp"],
  },
  {
    id: "out-wood-home-improvements",
    name: "Out Wood Home Improvements",
    industry: "Home Improvement",
    description: "Quality home improvement and renovation services for Sydney homes",
    services: ["Web Design"],
    image: "/images/portfolio/Out Wood Home Improvements/Out Wood Home Improvements.webp",
    images: ["/images/portfolio/Out Wood Home Improvements/Out Wood Home Improvements.webp"],
  },
  {
    id: "pineapple-funding",
    name: "Pineapple Funding",
    industry: "Finance",
    description: "Innovative funding solutions for businesses and individuals",
    services: ["Web Design", "Branding"],
    image: "/images/portfolio/Pineapple Funding/Pineapple Funding.webp",
    images: [
      "/images/portfolio/Pineapple Funding/Pineapple Funding.webp",
      "/images/portfolio/Pineapple Funding/Pineapple Funding 1.webp",
      "/images/portfolio/Pineapple Funding/Pineapple Funding 2.webp",
      "/images/portfolio/Pineapple Funding/Pineapple Funding 3.webp",
    ],
  },
  {
    id: "showfreight",
    name: "Showfreight",
    industry: "Logistics",
    description: "Professional freight and logistics services for exhibitions and events",
    services: ["Web Design"],
    image: "/images/portfolio/Showfreight/Showfreight.webp",
    images: ["/images/portfolio/Showfreight/Showfreight.webp"],
  },
  {
    id: "south-pacific-aromas",
    name: "South Pacific Aromas",
    industry: "Essential Oils",
    description: "Premium essential oils and aromatherapy products from the South Pacific",
    services: ["Web Design", "E-commerce"],
    image: "/images/portfolio/South Pacific Aromas/South Pacific Aromas.webp",
    images: ["/images/portfolio/South Pacific Aromas/South Pacific Aromas.webp"],
  },
  {
    id: "ts-road-works",
    name: "T&S Road Works",
    industry: "Civil Construction",
    description: "Professional road construction and maintenance services",
    services: ["Web Design"],
    image: "/images/portfolio/T&S Road Works/T & S Roadworks.webp",
    images: ["/images/portfolio/T&S Road Works/T & S Roadworks.webp"],
  },
  {
    id: "takeaway-packaging",
    name: "Takeaway Packaging",
    industry: "Packaging Solutions",
    description: "Eco-friendly takeaway packaging solutions for restaurants and cafes",
    services: ["Web Design", "E-commerce"],
    image: "/images/portfolio/Takeaway Packaging/Takeaway Packaging.webp",
    images: [
      "/images/portfolio/Takeaway Packaging/Takeaway Packaging.webp",
      "/images/portfolio/Takeaway Packaging/Takeaway Packaging 1.webp",
      "/images/portfolio/Takeaway Packaging/Takeaway Packaging 2.webp",
      "/images/portfolio/Takeaway Packaging/Takeaway Packaging 3.webp",
      "/images/portfolio/Takeaway Packaging/Takeaway Packaging 4.webp",
    ],
  },
];
